//
//  RustTemplate.swift
//  BRT Studio - Rust Project Templates
//
//  Copyright © 2025 Black Room Technologies. All rights reserved.
//

import Foundation

enum RustTemplate {

    static func generateCargoToml(projectName: String, isCLI: Bool) -> String {
        let dependencies = isCLI ? """
        clap = { version = "4.4", features = ["derive"] }
        """ : ""

        return """
        [package]
        name = "\(projectName.lowercased())"
        version = "0.1.0"
        edition = "2021"
        authors = ["Generated by BRT Studio"]

        [dependencies]
        \(dependencies)

        [dev-dependencies]
        """
    }

    static func generateCLIMain(projectName: String) -> String {
        return """
        use clap::Parser;

        /// \(projectName) - A CLI tool
        #[derive(Parser, Debug)]
        #[command(author, version, about, long_about = None)]
        struct Args {
            /// Input file
            #[arg(short, long)]
            input: Option<String>,

            /// Verbose output
            #[arg(short, long)]
            verbose: bool,
        }

        fn main() {
            let args = Args::parse();

            if args.verbose {
                println!("Running in verbose mode");
            }

            match &args.input {
                Some(file) => {
                    println!("Processing file: {}", file);
                    // TODO: Implement your logic here
                }
                None => {
                    println!("No input file specified");
                }
            }

            println!("Welcome to \(projectName)!");
        }

        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn test_example() {
                assert_eq!(2 + 2, 4);
            }
        }
        """
    }

    static func generateLibMain() -> String {
        return """
        pub fn add(left: usize, right: usize) -> usize {
            left + right
        }

        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn it_works() {
                let result = add(2, 2);
                assert_eq!(result, 4);
            }
        }
        """
    }
}
