//
//  PythonTemplate.swift
//  BRT Studio - Python Project Templates
//
//  Copyright © 2025 Black Room Technologies. All rights reserved.
//

import Foundation

enum PythonTemplate {

    static func generatePyprojectToml(projectName: String, spec: ProjectSpecification) -> String {
        let dependencies = spec.requiresGUI ? """
        "PySide6>=6.5.0",
        """ : ""

        return """
        [tool.poetry]
        name = "\(projectName.lowercased())"
        version = "0.1.0"
        description = "\(spec.purpose)"
        authors = ["Generated by BRT Studio"]
        license = "\(spec.license.rawValue)"
        readme = "README.md"

        [tool.poetry.dependencies]
        python = "^3.11"
        \(dependencies)
        click = "^8.1.7"

        [tool.poetry.group.dev.dependencies]
        pytest = "^7.4.0"
        black = "^23.7.0"
        ruff = "^0.0.285"

        [tool.poetry.scripts]
        \(projectName.lowercased()) = "\(projectName.lowercased()).main:main"

        [build-system]
        requires = ["poetry-core"]
        build-backend = "poetry.core.masonry.api"

        [tool.black]
        line-length = 100
        target-version = ['py311']

        [tool.ruff]
        line-length = 100
        target-version = "py311"
        """
    }

    static func generateInit() -> String {
        return """
        \"\"\"
        Project package initialization
        \"\"\"

        __version__ = "0.1.0"
        """
    }

    static func generateMain(spec: ProjectSpecification) -> String {
        if spec.requiresGUI {
            return """
            \"\"\"
            Main application entry point
            \"\"\"

            import sys
            from PySide6.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout, QLabel, QPushButton

            class MainWindow(QMainWindow):
                def __init__(self):
                    super().__init__()
                    self.setWindowTitle("Application")
                    self.setGeometry(100, 100, 800, 600)

                    # Central widget
                    central_widget = QWidget()
                    self.setCentralWidget(central_widget)

                    # Layout
                    layout = QVBoxLayout()
                    central_widget.setLayout(layout)

                    # Widgets
                    label = QLabel("Welcome to your application!")
                    button = QPushButton("Click Me")
                    button.clicked.connect(self.on_button_click)

                    layout.addWidget(label)
                    layout.addWidget(button)

                def on_button_click(self):
                    print("Button clicked!")

            def main():
                app = QApplication(sys.argv)
                window = MainWindow()
                window.show()
                sys.exit(app.exec())

            if __name__ == "__main__":
                main()
            """
        } else {
            return """
            \"\"\"
            Main application entry point
            \"\"\"

            import click

            @click.command()
            @click.option('--verbose', '-v', is_flag=True, help='Enable verbose output')
            @click.argument('input_file', required=False)
            def main(verbose: bool, input_file: str):
                \"\"\"Main CLI entry point\"\"\"
                if verbose:
                    click.echo("Running in verbose mode")

                if input_file:
                    click.echo(f"Processing file: {input_file}")
                else:
                    click.echo("Welcome to your application!")

            if __name__ == "__main__":
                main()
            """
        }
    }

    static func generateTests() -> String {
        return """
        \"\"\"
        Test suite
        \"\"\"

        def test_example():
            assert 2 + 2 == 4

        def test_another():
            result = "hello".upper()
            assert result == "HELLO"
        """
    }
}
