//
//  GeneratedProject.swift
//  BRT Studio - Generated Project Model
//
//  Copyright © 2025 Black Room Technologies. All rights reserved.
//

import Foundation

/// Represents a project generated by the Co-Pilot
struct GeneratedProject: Identifiable, Codable {
    let id: UUID
    let name: String
    let description: String
    let stack: TechStack
    let architecture: ProjectArchitecture
    let createdAt: Date
    var lastModified: Date
    let outputPath: URL
    let metadata: ProjectMetadata

    init(
        id: UUID = UUID(),
        name: String,
        description: String,
        stack: TechStack,
        architecture: ProjectArchitecture,
        createdAt: Date = Date(),
        outputPath: URL,
        metadata: ProjectMetadata = ProjectMetadata()
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.stack = stack
        self.architecture = architecture
        self.createdAt = createdAt
        self.lastModified = createdAt
        self.outputPath = outputPath
        self.metadata = metadata
    }
}

/// Technology stack selected for the project
struct TechStack: Codable, Equatable {
    let type: StackType
    let platform: Platform
    let language: ProgrammingLanguage
    let framework: String
    let buildSystem: BuildSystem
    let packageManager: PackageManager?
    let additionalTools: [String]

    enum StackType: String, Codable, CaseIterable {
        case macOSNative = "macOS Native"
        case crossPlatformGUI = "Cross-Platform GUI"
        case cli = "CLI Tool"
        case pythonScript = "Python Script"
        case webApp = "Web Application"
        case library = "Library"
    }

    enum Platform: String, Codable, CaseIterable {
        case macOS = "macOS"
        case iOS = "iOS"
        case multiOS = "Multi-OS"
        case web = "Web"
    }

    enum ProgrammingLanguage: String, Codable, CaseIterable {
        case swift = "Swift"
        case rust = "Rust"
        case python = "Python"
        case typescript = "TypeScript"
        case javascript = "JavaScript"
    }

    enum BuildSystem: String, Codable, CaseIterable {
        case xcodebuild = "xcodebuild"
        case swiftpm = "Swift Package Manager"
        case cargo = "Cargo"
        case npm = "npm"
        case poetry = "Poetry"
        case make = "Make"
    }

    enum PackageManager: String, Codable, CaseIterable {
        case spm = "SPM"
        case cargo = "Cargo"
        case npm = "npm"
        case pip = "pip"
        case poetry = "Poetry"
    }

    /// Decision rules for stack selection
    static func decide(
        purpose: String,
        platform: Platform,
        requiresGUI: Bool,
        needsOffline: Bool,
        needsPerformance: Bool
    ) -> TechStack {
        // Implement decision logic based on requirements
        if platform == .macOS && requiresGUI && needsPerformance {
            return .swiftUIMacOS
        } else if !requiresGUI && needsPerformance {
            return .rustCLI
        } else if requiresGUI && platform == .multiOS {
            return .tauriApp
        } else if purpose.lowercased().contains("script") {
            return .pythonScript
        } else {
            return .swiftUIMacOS
        }
    }

    // Predefined stacks
    static let swiftUIMacOS = TechStack(
        type: .macOSNative,
        platform: .macOS,
        language: .swift,
        framework: "SwiftUI",
        buildSystem: .swiftpm,
        packageManager: .spm,
        additionalTools: ["git", "xcodebuild"]
    )

    static let tauriApp = TechStack(
        type: .crossPlatformGUI,
        platform: .multiOS,
        language: .rust,
        framework: "Tauri",
        buildSystem: .cargo,
        packageManager: .cargo,
        additionalTools: ["npm", "git"]
    )

    static let rustCLI = TechStack(
        type: .cli,
        platform: .multiOS,
        language: .rust,
        framework: "clap",
        buildSystem: .cargo,
        packageManager: .cargo,
        additionalTools: ["git"]
    )

    static let pythonScript = TechStack(
        type: .pythonScript,
        platform: .multiOS,
        language: .python,
        framework: "Click",
        buildSystem: .poetry,
        packageManager: .poetry,
        additionalTools: ["git", "pytest"]
    )
}

/// Project architecture decisions
struct ProjectArchitecture: Codable {
    let pattern: ArchitecturePattern
    let modules: [Module]
    let features: [String]
    let testing: TestingStrategy

    enum ArchitecturePattern: String, Codable {
        case mvvm = "MVVM"
        case mvc = "MVC"
        case clean = "Clean Architecture"
        case modular = "Modular"
        case simple = "Simple"
    }

    struct Module: Codable, Identifiable {
        let id: UUID
        let name: String
        let purpose: String
        let dependencies: [String]

        init(id: UUID = UUID(), name: String, purpose: String, dependencies: [String] = []) {
            self.id = id
            self.name = name
            self.purpose = purpose
            self.dependencies = dependencies
        }
    }

    enum TestingStrategy: String, Codable {
        case unit = "Unit Tests"
        case integration = "Unit + Integration"
        case full = "Full Test Suite"
        case minimal = "Minimal"
    }
}

/// Project metadata
struct ProjectMetadata: Codable {
    var license: License = .apache2
    var author: String = "Black Room Technologies"
    var version: String = "0.1.0"
    var repository: String?
    var tags: [String] = []
    var notes: String = ""

    enum License: String, Codable, CaseIterable {
        case apache2 = "Apache 2.0"
        case mit = "MIT"
        case gpl3 = "GPL-3.0"
        case bsd3 = "BSD-3-Clause"
        case proprietary = "Proprietary"
    }
}
